### ISSUE TITLE
Set logLevel from code

### ISSUE THREAD

**Issue by Supergiovane** [rodney42/node-hue#1]
Hi,
thank you very much for this contribution. I use it in my KNX node for node-red.
Is there a way to set the logLevel by code, as you do, for example, with *host* property?
Thank you.

**Comment by rodney42** [comment]
Hi,
Nice to hear, that you find this library useful. Thanks.
As a workaround or solution, you can set the environment variable LOG_LEVEL programmatically with :
`process.env.LOG_LEVEL='WARN'`
before calling hue.connect().

But the logging lacks flexibility - so I just provided the possibility to use a own implementation as option. This is new in version 1.0.4. For a example see [Custom logging example](https://github.com/rodney42/node-hue/blob/main/examples/customlog.js).

Greetings

**Comment by Supergiovane** [comment]
Thank you so much.
